# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_articlemce'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleMCE',
        ),
    ]
