# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20160310_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
        migrations.AlterField(
            model_name='blog',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Classification', verbose_name='\u5206\u7c7b'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='clicked',
            field=models.IntegerField(blank=True, default=0, verbose_name='\u70b9\u51fb\u91cf'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, to='article.Tag', verbose_name='\u6807\u7b7e'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=100, verbose_name='\u6807\u9898'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
    ]
